config:
  clm-hosted:runpodApiKey:
    secure: AAABAHnj5YYk72Nmx8ykWnsQdr/EnEcN/F9KRX5lcJPgfDH6aF23ZkQzqcjEzaUvHqp37/4D1cgVIu7zc218vQyDjbxzVJNNfg//32W41TSCVg==
  clm-hosted:cloudflareApiToken:
    secure: AAABANhSsQMPJiFCjixpZ5d7c5Bqi9Mzzf4PHCKLinlb4kio2LN+3VTV4kYYT+tALmq9t4BIPhxO30qRpxAL19XNSbDlimiHxRb//xJgAdqrRH1QZg==
  clm-hosted:clmApiKey:
    secure: AAABAOxC7bG9WUvDq2UV7Y7ArlV5Vb6w1wWXAEllBw932alnN0usKgYxa6ROpSD4zQKKTZlueRPo4dhmw7+N+wVk9MMom4ZF1FSIOBhZXc632RA3CdQy4YUEN3T2H/fe
  clm-hosted:agentKeys:
    secure: AAABACpaffoN+1s9H8hso05pUtsCOSIz7Xq9d6GtPELXpyp8la3dZea3sZXKcsIRUEEnLekO6b8pdmkWuhzRsiYCLj1n2D0Brlgqc+e1KNJg/FIqa9tc6ax8+cDP2FLZ/M4zB52lurlNG8ehRA==
  clm-hosted:registryAuthId: cmuddk8gr003psxunmobd4qxd
  clm-hosted:cloudflareAccountId: daa733811c7150ec3148993b991a2400
  clm-hosted:cloudflareZoneId: f8a3822c528b323b90dc68789244791e
  clm-hosted:imageTag: 19dea705c6506c0fa23cfc4d63641d0ecc2ce3df
  clm-hosted:adminAgents:
    - admin
    - jt@metatheory.gg
  clm-hosted:accessTeamDomain: metatheory.cloudflareaccess.com
  clm-hosted:googleClientId: 374857321431-foqij8lbrqfo02i6vg76c52ksnpko26o.apps.googleusercontent.com
  clm-hosted:googleClientSecret:
    secure: AAABAGVApCxrt7NcAuz2WvvEAJdL+PMUuxP9d+M9uvhFZAqNZfNjzPWz1TLYCvq4crwNQt5x71fDD35GvRkCI6+Rpg==
  clm-hosted:decisionReaders:
    - jt@metatheory.gg
  clm-hosted:anthropicApiKey:
    secure: AAABAD+VC5uV5/CYJqQLpyNkN/mcDob0IQ0ynFzLr+G676b6pBYyqfWvoHAlk7uURixBufxofv+r01xPG/fzjvQhUKcEVOEEjePkXzr9zBneEcVU+DzZfYtCE8WjsYW65pgyPfGXXe/u5qxKT8CeA2NOGMYtuim6OJQLI7ikn4vXgpjfEaVoSRG8
