config:
  clm-hosted:runpodApiKey:
    secure: AAABAHnj5YYk72Nmx8ykWnsQdr/EnEcN/F9KRX5lcJPgfDH6aF23ZkQzqcjEzaUvHqp37/4D1cgVIu7zc218vQyDjbxzVJNNfg//32W41TSCVg==
  clm-hosted:cloudflareApiToken:
    secure: AAABANhSsQMPJiFCjixpZ5d7c5Bqi9Mzzf4PHCKLinlb4kio2LN+3VTV4kYYT+tALmq9t4BIPhxO30qRpxAL19XNSbDlimiHxRb//xJgAdqrRH1QZg==
  clm-hosted:clmApiKey:
    secure: AAABAOxC7bG9WUvDq2UV7Y7ArlV5Vb6w1wWXAEllBw932alnN0usKgYxa6ROpSD4zQKKTZlueRPo4dhmw7+N+wVk9MMom4ZF1FSIOBhZXc632RA3CdQy4YUEN3T2H/fe
  clm-hosted:agentKeys:
    secure: AAABAPTeBtLWUR1cEecBCCU0IWEUHtxeeX+0mEQxaJLAVv+XM/dhTkFMQ4aHHj1VX1b3mTqNuZ7mT412JF9Hq9dNvRZIjwtOQfTX+HMMtSc5BAY+YbakMc8I9B+TIGvILHGa19g6k1r2c0JCEBnaTryCefOzu8L9qDQ5gdfTdwoW/VniZR2Ij1yCTa16MiAlnIY5KDigYpe2mY87x/pOc3lgrBdB3v5OD2hjFHvdXG6azUdBR/8bJ9MdmJE=
  clm-hosted:registryAuthId: cmuddk8gr003psxunmobd4qxd
  clm-hosted:cloudflareAccountId: daa733811c7150ec3148993b991a2400
  clm-hosted:cloudflareZoneId: f8a3822c528b323b90dc68789244791e
  clm-hosted:imageTag: 126a4200ebb6e142b12f0231efef07f743c81ae0
  clm-hosted:adminAgents:
    - admin
